### ISSUE TITLE
Copied

### ISSUE THREAD

**Issue by talonbragg** [FootballCoder/Sweep#1]
Just saying the design of the website is kind of copied from Wing. But then Wing is copied from skeleton so I don't really care. I just wanted to let you know. Try to change the design a bit. 😄

**Comment by FootballCoder** [comment]
If you think I copied to tell the creator of Wing. He'll vouch for me.

**Comment by talonbragg** [comment]
Well, I also said that kabir copied from [skeleton](http://getskeleton.com). Its not your fault that it is a copy.
